apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-ui-deployment
  labels:
    app: weather-ui
spec:
  selector:
    matchLabels:
      app: weather-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: weather-ui
    spec:
      containers:
        - name: weather-ui
          image: vinayakasgadag/dcoders-weather-ui:milestone2
          resources:
            limits:
              cpu: 2
              memory: "2Gi"
            requests:
              cpu: 1
              memory: "1Gi"
          ports:
            - containerPort: 3000
