apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: datasource-deployment
  labels:
    app: datasource
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datasource-deployment
  minReplicas: 2
  maxReplicas: 7
  targetCPUUtilizationPercentage: 60

