---
#resource_types:
#- name: kubernetes
#  type: docker-image
#  source:
#    repository: zlabjp/kubernetes-resource

resource_types:
- name: k8s
  type: docker-image
  source:
    repository: kudohn/concourse-k8s-resource

#- name: source-code
#  type: docker-image
#  source: {repository: concourse/git-resource:ubuntu}

resources:
  - name: git-ds
    type: git
    source:
      uri: https://github.com/airavata-courses/DCoders.git
      branch: feature/30-implement-cd
#  - name: docker-ds
#    type: docker-image
#    source:
#      repository: vinayakasgadag/decoders-datasource
#      username: vinayakasgadag
#      password: 1234@kuby
#      tag: milestone2
  - name: k8s
    type: k8s
    source:
      api_server_url: https://192.168.49.2:8443
      api_server_cert: |
        -----BEGIN CERTIFICATE-----
        MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
        a3ViZUNBMB4XDTIyMDMwMjIwMDIyNloXDTMyMDIyOTIwMDIyNlowFTETMBEGA1UE
        AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM/S
        GgeQX5EIjXhff3FQu0dprB4T+L9v/SVPcWd+hlvVTfir+r115iC5XFtpppb1i8Ys
        ZWg+oD4l8M29ep53Z/E1Cfqr3Hxzjaa+FodQ5H93TIl7gY9Cf1E36rPCmBQtL54Z
        m6+VQR6ez1hkdfPFqRG9euaUUmF1EsscCdsFb9JV6LlyVCGJwDIKR4MR5XQeQhrp
        vWFg+8eMebzRnJ8jxEIup8Q2JIL63PRn0gwa8oR84BSmeDvCfEYaBtmR33+/PVV7
        xwOJRdRgqoA9/n7fYQnoF0fnGa9XLepn4qmk2au50IQex7xekDP0baiLeh3x9+kI
        zs2JrSuGehcoGvjqYkcCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
        MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
        BBRXhLsUO+d890Fa4reeRPRyrrp0YDANBgkqhkiG9w0BAQsFAAOCAQEAcjYN/Kcu
        jBrvH/KgT+Go2oHeYR64WDmEOOZowUTT/XtHH5g8RHuLcII1MuMrksjDRUcDNsd2
        gBz2Y/MdUIklSose0egA8tJpelNDhsizqwqYCXbPFY0dLX6n23vI4cSjpm83/bgo
        tIfAhr2ouxRyJ53YpYcHmn7btWuGvrN0KB3tjWIxKZ0VHF+vSeKpqz+2WOWS75Su
        WlTq7iAk3ozDzOOlnlOsFmmUBqr0jS3duQSXyQ8Ft0/S8cGDLSxNlbwj8CBUarzt
        q0tmudAE5fM++i8STd6tg5mARWu0zOnTNOHIYroptcQuSP2jSijVyGbRctNIFLQh
        cl7rE0oqLLVQnw==
        -----END CERTIFICATE-----
      client_cert: |
        -----BEGIN CERTIFICATE-----
        MIIDITCCAgmgAwIBAgIBAjANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
        a3ViZUNBMB4XDTIyMDQwNjAwMzAyNFoXDTI1MDQwNjAwMzAyNFowMTEXMBUGA1UE
        ChMOc3lzdGVtOm1hc3RlcnMxFjAUBgNVBAMTDW1pbmlrdWJlLXVzZXIwggEiMA0G
        CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC6pRQq8Kl0gvsM4j/lnOGcR8hwJmJL
        p+lXNcbXZDB8w4QFqHnOv28R7+OKTr7r3EOGSCKW9tE+l9/a+BTUygKFTcyLcNUR
        JNaKkAnHm3V8OmJvoZfw2K3pYXIF4NtoqGLFgT38/4w6NNHfS/jm/bkDcRio40xa
        l13iaWyr4BL5Efp/RLAqiWf4tUCxQ1TfW7t0FfxdVN/xcTd7JLrHUdVl1BsvKWJG
        zjwAVg6ZxF56U62L2N3VKhubsIVTqZ4XMo5iShvVDvsLCwNWOC20Hd93hvcYYQ5j
        W6UHF4PN+/7gtBWGqCNNzt2sHJJJvgCPMgOylrJZw6MmPVCfE7+UBqjFAgMBAAGj
        YDBeMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
        AwIwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBRXhLsUO+d890Fa4reeRPRyrrp0
        YDANBgkqhkiG9w0BAQsFAAOCAQEAcwVbfqyKOvatRwJ3RO+fzKKlH5cO0xiZ7FRg
        0VTFVPZ8oX1cylW1rhD9173U7aQg1bJsmFSnKKd/bWSixbhDn3NEYtk6tlTPsiQ5
        W1nJ4QaL5/ncqm3fF8XCkXV3WutC6l501eSRqoB24NUp7pmTM9Qgr+l+QYn48bOi
        lf9DeonAhX7ra449jkNP/LYEruwrLjs9o1Zv9Buo7ba+SbQXiWchw2XjjBOuQ/dE
        I152FC4QQkk3+CKM/ShM6ctn7aqfgoph9Y5wgm/wsfVK2DCpITIioPKRUtGtjMtS
        KxqvlYZbH/fVIkF724jPKesag03GDmQ+mYVRMVrBhKTji1lG0A==
        -----END CERTIFICATE-----
      client_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEAuqUUKvCpdIL7DOI/5ZzhnEfIcCZiS6fpVzXG12QwfMOEBah5
        zr9vEe/jik6+69xDhkgilvbRPpff2vgU1MoChU3Mi3DVESTWipAJx5t1fDpib6GX
        8Nit6WFyBeDbaKhixYE9/P+MOjTR30v45v25A3EYqONMWpdd4mlsq+AS+RH6f0Sw
        Koln+LVAsUNU31u7dBX8XVTf8XE3eyS6x1HVZdQbLyliRs48AFYOmcReelOti9jd
        1Sobm7CFU6meFzKOYkob1Q77CwsDVjgttB3fd4b3GGEOY1ulBxeDzfv+4LQVhqgj
        Tc7drBySSb4AjzIDspayWcOjJj1QnxO/lAaoxQIDAQABAoIBAF2o7yjpIa/k9oQt
        mPDpO9HHt86HhHYAqbhotQJrNWW2Wy7Xr2BPcjYnEiDaiTYkjwH4etsUukXVwrDI
        IvPw9zjbpJQop9L1kG9x/mZbHaacSb9I8M0cfpEJpEVM4+1t6jrAM1IdDso6rUKH
        hjyr/8a5Xy2I+kzPfn5advz88ahoP4WmxPOR3pOtTWygHcHR8Ppe9dQt5kCj19gD
        F2Y7Jkxea7xFpiK+L5F+/Iuxe8kpDs7o/5BoudTRLhX4CqwVSEl5GshiFvCc9iTA
        9K5FdHymT6sX3dRSaCB/iaRM6lk9VEcFGogcPbapeQGq+ZERia59chJMhCAzutE2
        aByT8VUCgYEA86cad1UVtIuMLSoqS+3Tcm80iDzVANXhI7mcIdSMsj7p6qRPF9Fw
        /oGZdZi4JWIaP+OZ90WYhhfLkG1Afg9OCIrwDDVAGZuIuPazPqrKBltAIjSYHec0
        7YqHg5fIx4D1kvP0Pr28fMK5JM6qbiTHYVsNyq+o7ydy1VyxVX1bHIsCgYEAxBpq
        DEoviIH3+PntMu6fl8EOobnT3ide6IAJni1DqHfvbXbUI1ztUO1OsRlJoQxK1Ym7
        p6FCjoFTUn0axZe45ajCl+4cVscDIxKgOMxMUJj7THnMZ2s0AD0dqDxQau2BXGOB
        AsOQ9ZVdK/W1mU/rD3IMAKlgNIfbV4uzzcYGae8CgYB740yevqGRsp7s3BKzltK7
        zfWNDDlV+mpGivrrbLK5cynnR/J7buAgWG9aDvQa9f3Y3HaN91ItZG36GsL/FfMc
        fuC9pFnaa24idjX/uEGO59j9S3bJRaVw3s42x/esEVNMjER1nm33ld8j6v1XkdXb
        F7w0ggrIx2spN79nc5zfLwKBgQC3jDWoTSOSdHvCCUOvwVOVObjVPNaGf3lAyt61
        s445OBDc9zT16HujnIpkDtQwrg25MtJ2wuRF99wiQEB3o1wHcV65z7+spVdVU5Ct
        uOLRKW9FFFdykQ+6DXodxl5KxwSmkefly2B5zJTJmZCg8AGGkmuTjvUiFesCVRs1
        Rd0o9wKBgQCjtdMPk4f0PggiAaCBPNPR2UdRKdXGnqjmZk8oBEqn7BhJiZ0gq/9E
        smky3Pixlz1KdQf1AeNl+KqPVdzCpvowYAvjdjrqJvgw/pdYdTk0jEdfPIwFPggQ
        LJyt2vrH5MrhrYkrRoDP/XuF6QFXqOltmalGeaz/6Z1fwJgjsCdORw==
        -----END RSA PRIVATE KEY-----
      skip_tls_verify: false

jobs:
#  - name: "docker-build"
#    public: true
#    plan:
#      - get: git-ds
#        trigger: true
#      - put: docker-ds
#        params:
#          build: /datasource_service
  - name: "deploy-application"
    plan:
      - get: git-ds
        trigger: true
#      - put: git-ds
#        params:
#          path: /tmp/
#        passed:
#          - "docker-build"
#      - task: copy-config
#        config:
#          platform: linux
#          image_resource:
#            type: registry-image
#            source: {repository: busybox}
#          run:
#            path: cp
#            args: ["/tmp/DCoders/deployment_scripts/k8s/config", "/tmp/"]
      - put: k8s
        params:
          status_check_timeout: 60
          command_timeout: 30
          paths:
            - datasource_service/k8s_deployments/deployment.yaml
