---
resource_types:
- name: k8s
  type: docker-image
  source:
    repository: kudohn/concourse-k8s-resource

resources:
  - name: git-ds
    type: git
    icon: git
    source:
      uri: https://github.com/airavata-courses/DCoders.git
      branch: feature/30-implement-cd

  # Where we will push the image
  - name: build-image
    type: registry-image
    icon: docker
    source:
      repository: vinayakasgadag/decoders-datasource
      username: vinayakasgadag
      password: 9b770f15-c13f-41cd-a4df-6a1a175141a6

  - name: k8s
    type: k8s
    icon: kubernetes
    source:
      api_server_url: https://192.168.49.2:8443
      api_server_cert: ((k8s-secret.api_server_cert))
      client_cert: ((k8s-secret.client_cert))
      client_key: ((k8s-secret.client_key))
      skip_tls_verify: false

jobs:
  - name: "build-publish"
    public: true
    serial: true
    plan:
      - get: git-ds
        trigger: true
      - task: build-image-task
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
          inputs:
            - name: git-ds
          outputs:
            - name: image
          params:
            CONTEXT: git-ds/datasource_service
            UNPACK_ROOTFS: true
          run:
            path: build
      - put: build-image
        params:
          image: image/image.tar
          version: milestone3

  - name: "deploy-application"
    plan:
      - get: git-ds
        passed: ["build-publish"]
      - task: create-deploy-scripts
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          inputs:
            - name: git-ds
          outputs:
            - name: deploy-files
          run:
            path: git-ds/deployment_scripts/copy_files.sh

      - put: k8s
        params:
          status_check_timeout: 60
          command_timeout: 30
          paths:
            - deploy-files/datasource_service/deployment.yaml
            - deploy-files/datasource_service/service.yaml
            - deploy-files/datasource_service/autoscaler.yaml
          watch_resources:
            - name: datasource-deployment
              kind: Deployment
