---
resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource

resources:
  - name: git-ds
    type: git
    source:
      uri: https://github.com/airavata-courses/DCoders
      branch: main
#  - name: docker-ds
#    type: docker-image
#    source:
#      repository: vinayakasgadag/decoders-datasource
#      username: vinayakasgadag
#      password: 1234@kuby
#      tag: milestone2
  - name: k8s
    type: kubernetes
    source:
      server: https://192.168.49.2:8443
jobs:
#  - name: "docker-build"
#    public: true
#    plan:
#      - get: git-ds
#        trigger: true
#      - put: docker-ds
#        params:
#          build: /datasource_service
  - name: "deploy-application"
    public: true
    plan:
      - get: git-ds
        trigger: true
#        passed:
#          - "docker-build"
      - task: copy-config
        config:
          platform: linux
          run:
            path: cp
            args: ["../k8s/config", "/tmp/"]
      - put: k8s
        params:
          context: minikube
          kubeconfig_file: /tmp/config
          kubectl: delete pods -l app=datasource
          wait_until_ready: 300
