---
resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource

- name: git
  type: registry-image
  source:
    repository: concourse/git-resource
    tag: ubuntu

resources:
  - name: git-ds
    type: git
    source:
      uri: https://github.com/airavata-courses/DCoders.git
      branch: feature/30-implement-cd
#  - name: docker-ds
#    type: docker-image
#    source:
#      repository: vinayakasgadag/decoders-datasource
#      username: vinayakasgadag
#      password: 1234@kuby
#      tag: milestone2
  - name: k8s
    type: kubernetes
    source:
      server: https://192.168.49.2:8443
      context: minikube
jobs:
#  - name: "docker-build"
#    public: true
#    plan:
#      - get: git-ds
#        trigger: true
#      - put: docker-ds
#        params:
#          build: /datasource_service
  - name: "deploy-application"
    public: true
    plan:
      - get: git-ds
        trigger: true
#      - put: git-ds
#        params:
#          path: /tmp/
#        passed:
#          - "docker-build"
#      - task: copy-config
#        config:
#          platform: linux
#          image_resource:
#            type: registry-image
#            source: {repository: busybox}
#          run:
#            path: cp
#            args: ["/tmp/DCoders/deployment_scripts/k8s/config", "/tmp/"]
      - put: k8s
        params:
          kubectl: delete pods -l app=datasource
          wait_until_ready: 300
