---
resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource

resources:
  - name: git-ds
    type: git
    source:
      uri: https://github.com/airavata-courses/DCoders
      branch: feature/30-implement-cd
#  - name: docker-ds
#    type: docker-image
#    source:
#      repository: vinayakasgadag/decoders-datasource
#      username: vinayakasgadag
#      password: 1234@kuby
#      tag: milestone2
  - name: k8s
    type: kubernetes
    source:
      server: https://192.168.49.2:8443
jobs:
#  - name: "docker-build"
#    public: true
#    plan:
#      - get: git-ds
#        trigger: true
#      - put: docker-ds
#        params:
#          build: /datasource_service
  - name: "deploy-application"
    public: true
    plan:
      - get: git-ds
        trigger: true
#      - put: git-ds
#        params:
#          path: /tmp/
#        passed:
#          - "docker-build"
#      - task: copy-config
#        config:
#          platform: linux
#          image_resource:
#            type: registry-image
#            source: {repository: busybox}
#          run:
#            path: cp
#            args: ["/tmp/DCoders/deployment_scripts/k8s/config", "/tmp/"]
      - put: k8s
        params:
          context: minikube
          kubeconfig: |
            apiVersion: v1
            clusters:
            - cluster:
                certificate-authority: /home/exouser/.minikube/ca.crt
                extensions:
                - extension:
                    last-update: Tue, 05 Apr 2022 19:36:51 UTC
                    provider: minikube.sigs.k8s.io
                    version: v1.25.2
                  name: cluster_info
                server: https://192.168.49.2:8443
              name: minikube
            contexts:
            - context:
                cluster: minikube
                extensions:
                - extension:
                    last-update: Tue, 05 Apr 2022 19:36:51 UTC
                    provider: minikube.sigs.k8s.io
                    version: v1.25.2
                  name: context_info
                namespace: default
                user: minikube
              name: minikube
            current-context: minikube
            kind: Config
            preferences: {}
            users:
            - name: minikube
              user:
                client-certificate: /home/exouser/.minikube/profiles/minikube/client.crt
                client-key: /home/exouser/.minikube/profiles/minikube/client.key
          kubectl: delete pods -l app=datasource
          wait_until_ready: 300
