apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: vinayakasgadag/dcoders-api-gateway:milestone2
          resources:
            limits:
              cpu: 2
              memory: "5Gi"
            requests:
              cpu: 1
              memory: "2Gi"
          ports:
            - containerPort: 8081
