apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: um-deployment
  labels:
    app: um
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: um-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
