name: "gateway_service"

on:
  push:
    branches: [ main ]
    paths:
      - "gateway_service/**"
      - ".github/workflows/gateway_service.yaml"
  pull_request:
    branches: [ main ]
    paths:
      - "gateway_service/**"
      - ".github/workflows/gateway_service.yaml"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17]

    steps:
    - uses: actions/checkout@v2
    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.python-version }}
    - name: Install npm packages
      run: |-
        cd api_gateway
        npm ci
        npm install

    - name: build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: vinayakasgadag/dcoders-api-gateway
        tags: milestone1
        registry: docker.io
        directory: api_gateway
        dockerfile: api_gateway/Dockerfile
        username: vinayakasgadag
        password: 9b770f15-c13f-41cd-a4df-6a1a175141a6
